language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
jdk:
- oraclejdk8
branches:
  only:
  - master
  - stable
before_script:
- openssl aes-256-cbc -K $encrypted_48b404373410_key -iv $encrypted_48b404373410_iv
  -in secring.gpg.enc -out secring.gpg -d
script:
- ./gradlew clean build uploadArchives
env:
  global:
  - secure: YWoKIGKCB/DyVdGKjQHiiYwxhDgsWdXjkMbxsYXZQ7q8DTGLkUkAd7vRB+WVtmHZtvgfxccVrDJHwxd90pD/J/BWYA+1hz9bK2pwdRK9WYL7cb/8PJC7k5VG17ZJQ6bMHVtoNMbJ5h28rr8XQU8C0RzFB77N4+ua1aqNpgXYsnyixt6JMAwj45EeAMF+u0ni5dTIhGumadj2un0F4Ym5CbOIg9jybzc/dQYLubStTrYZWD0643oiPolU9rRXdZ94ngq/zW752dGxUgTl1DLY+4Ciz+1DFtbH+BNn0h4x78tz5v08w8q19lBi3hYCVwH7olcR5vhGl7mUGEkRwvANVjBdfznbR3OnJDeTfFeBL8id12L8d7udCBTPT5Ohft2LH+E8Ab4sUnE5D94mQvVT6+FfrH+93wWfbKyFEf9dplc/sekh8LHdwycPqcEm0jdRSpnqtuOHfhDa288UMy1pMxWlcUbxWDWxmQ0WoazQiUNSWENhzzy+hFmaDvcRa/6t9rk2zHuc0jMHYc/I4X1mUBtKmoLwU6e6gQBEDBejYgI3YPGQRsXGlcpSll0t4su39JdvRGdHAfUd19AccUTLj6DO5SyxjuHRR9suzUkEIqojXIw+XkpM2bQOTt/xjLKUgblhtq13efKjpdGW8Kz8t9A1EJYqOm9RT/WcvKUmB5Q=
  - secure: AI9E0GMQu1mBiikHVPW/KCHekc69Riq0pCK+aC6ozGQEVr2/TqGFmtv5BukoT1WjmQy8XgLixE7qpjFpW+v6oD83l945RsH1hpZAqyjg1gHsoofLqjOgTvoO5TjNfQfaue42vcZdeb8j9DDPau/lmaCv7OagrDBjMyYZHEA/FjyvcRkxiZZPW5bGZoAfcyAwiL/d6IE7O4drfI9587orUQ01pg7JB8DNSJM/FpgCpKPiPyufugam76UsM34Yi+p7UFrgS2dsQ5YHNMTaixV/AY+pu1tXKfN+u2KqzXP7iwMQAN95onJ+nKAHVQ/UiowHzG7tnKLFXqaybQt0vD53ZIged8rfT6nGoXp1YSJvvTeLhb5/x9XlhtfuR49ojnvyImmWt41mcr/kdHTGClXjCf1o1hWUazZte6ZYnCqqp3BhK/jqTjYURRuO9E0KzmFXR0K8cdycXtzpW6CkggX6q80+ILHOupAoY9Vsfzy65PcEKeWrqtZRY3SC39+ZbEQEwi9N3Tfa+VAk1kXXZGbtjdrgLJJYpO7/cuLAXfww2viiY5bHW2x2sokqi+J70GEI1VsBGJj8cqkBPdOKZBBd8xPsAiApfKCprEH0zLtPpQS/OjC7U7oyLmIAHGtKDr0Gp+fAZyoIqYN2qmicCpFeRFOaxoQgxHubHf6f+rJyqtc=
  - secure: feKp29w3L675eWTYpArKKGkNz76VSbLU36CiY/ALqdxyOr08VBRB4wGsifxm5Wx+NZQOVRkl0E39+2iM517qFFEd5oI6HwwQ0FuY8WLDkSzXBEyfMMzGjpVaHpsTTXkDE47OL1cmO5+6RY8WYxxd1r71YGyVPt1+iFn0k7w0q0jlVnvQuFkHJY7Bcr9FE4aLm+06TJ50BWJVaMjf7E6TUlvVpm7o3Rrkt85zUVyQXUfX7AE8OES/D0oN0FgPavCRMPS44TaP7YohnJjSkmKcuVOy8ZwrIOOLhMpEtj4VSwO+xuHK7Y/kaGLGURcxeQIP3Hx6C6A8R0uI51kTatrugvQGKtonOkiNXAVypDkaiOZaP2XF3zo1syKVwXJnL0rz4wo4fU7OFH3jUdSbW+NrBNOo5ySMKZzZDK71GLpBjSjIK0On4ZwE0g5gVpGXuVyVhtPgu7m8qPgj3tMZdqE3w5mQ+LdZlLu+dcQYBxk1czzISCvkQ+W1WDp/BYQa1kYwR0qJNuYSYc2zhhGedmPJshMTkmMGUJnlVeatOFUk0GfHgP/tUIZ4wMH30CEamas+nZ7QY1FLedsySCp/c8+QjjvxL2IjIUKvBTxN4S5C0rQQEo7aXgr1A5HtjeThBU+Z+c5i7DCQQxKzK8tetfzIiFgHSNPrqfNEHaf+fHgDC8I=
  - secure: f6KZmvJ1pO9I2D48a+vNdiYa3+mW4tUkDh14ZPEMtNLoMDejbqmvd0URJHF1Po1gV2DgO80F26GyTdhaFbLN7KUK+62OTT4q41AcxuSSlIErSM6qo2S3BYWMes7sjmFDNY8ySIc3CD82Uw3FGmEA8zZdYFqrgtjRNQQdtbyXMrla3utSdPJrysV9Q5Pc5PfShs3WPj0wToEiwBi8m/TZL/ruOhwjThOmc1OekTgWLc/5Rk3IGf8bld9Q7UFgnSQAgzp52SUktY3lXj+KJXQIpdA2wV6kb8GdRTDvdr9NGEmnf8X4pdg3h+jlJzwOvBTroOXdfwyPscFTBSgWgFov/+LQIjvckqXgNIz6oASURao3izQxRnKOrsje5rUKB3CqjiRB/pJTUtptExiTIAOym3ZE9u7IluD7uNb/WD8vjjEK4z4mDdiL0YegKQrncgJJpSSTFN+HSVfqzKn1A7ie175PnRpsWuhjYsC1SWzNsKWWy4GkzN4uW0iUEccEKq7CmvoPLnwJnnrIGeWKF+lZN/qVjvQsJZLC24KByFvwxFKEmWKq04b/NhSHozbEwAn4WHdrNJxwQLhkFvUfXiHrlk+Ji7jD/Hbx/GZI6LxkhmXWehVEYKj+jVJLuq/slzLSJUJNG1rSQ9x70u9ZXi1AquGHrVGlSRWQKHbLiz8Hego=
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
