language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master
  - develop

before_script: openssl aes-256-cbc -K $encrypted_d89d1ce6e9a7_key -iv $encrypted_d89d1ce6e9a7_iv -in secring.gpg.enc -out secring.gpg -d

script:
- ./gradlew clean build uploadArchives

env:
  global:
  - secure: jYLzkKzA3GPjc2hgNSvfCkpuGN8vS6tf8aA5mkDGLEeGAkTzu55aU9XRJM60pB+uIl3hRQf0CO5hj6wRe0wUgnSdHghvOkXGST++Yc7qOg+HFUbzRtmMP1aproADsH7MmYR6mzPlSKRD3rEKmlffD71pCqJz9FJW3Ptu+yRwlHSfZP49dOMcd6AzPy8eCdrhUgM6S4Cjpuhiq8BhiUQIjRHijwQ6kYk6Q0d+BRxCW9wT8b1D9iMWhug4YcxK4SPwjeV6QtLjqTj+ptZKUVxAvUigNDtpQGRayZay3EF2RsjeqBAV2HB6FR5lJahbU6ylm0PUF+I3UbG3N9wIkbPqG8Sbfax3kMUli+yYc2YAeiRgw170DAy+u1yrg36BdkUcZL5KQ0daAVB7dMSeJjrX+U8JK6SaW+BkaCuS/fnJ6mjphSalL/RU5Voqpr1GQPe1ol/I5v80V+o+yEqS8HvgQLBA3XpF/fOqkG0bAlUASXP+ut4fOq40kat9Y4s+abHEnu+7sRI+TklH9+JHoh2QGd5KJM+Z+7qJy3ThVIDb4FFRjYR5XmModZ3kjH5rofs5Rxuy1brd1qM8vnu2wxFHtKbUe2WxomS2tjn1Zftz828GxYWq8C9n9PeyCLYJrh/jSNPnCuroJJHBDGxG0Fy60dTsuE9DusUQprxu7llsS6c=
  - secure: k5TfUm3r71v54SwNJ0zF0iHf4B/WFSaoHpRYG8fBTS0Z5RwPfCEFbQsdpT4VHBZrVkflgCOHuXr2DknnH5cVfAzi1XG/gthJX/pX23m+nq+ix+EjClkIQm/buhOhlFtlJTBK5vJg7EBbbdkcL/4/+Vfs5/r+jB7GzTrHrnGN3sIQaGvwYzR8U+bMbCpdYvVjYV7l9VBwNrIwXJs+n96WNJp2qYB1xDMBALVUAgIqGteR/cl4wzIBI9sX5S09lmFqYxFLY+yXYsDY5Vw60PWpTxuLfzLmzowPXhabZbRsw89vIt1mWX81gDs5lxnlYDnXn7PQNAnbNhrlI23k65smJ0E0+Q+Av+jvUJuyUMccL7R0DL716P4chnZIEZmHs1mLKtUFEf5qIl4MnGVXn82m3NVQnl8mhSqxnFce7GglKSCFqcf+NmlmcoKbEs4Xu/xaiASabBxrn2knlonf9xxe6ErHjtGZ5abmsmKu2kz1fKstHbj8pniJunlhX+Z+94KXIzZj/6ySMjik/kyLt32smTsMT8bQliCdAYNqgPT3m324Bk76i+vfCz9/gP3e/lxUIVUMcRZ/4DVLaWuoTtbnxaRhIYe3aIZtZdrQFhlt2f479jqfq3Yd2NSD6UH+rFhuvK+F8CS242PohXlN1uvf1q9CpMjksWrRvzovsKLTZHo=
  - secure: T+LH/nITXPfzEBz5Qbe8SNUHvMPzBegxu4q0EwST1YXC/W5m9uZeJkua6ze3uIilgtPF4razqE3/tZidREnXPgSP/BmcuHBIQwQrURvwWgxqUm46hghnXhRsP1umBa9OYeYSSt7Spy8Yg7L6qdryIU0pkd9HQtDBiP6Nyx6ZuXsd5hEbHJnjtnSUvDWn8tW2cpQvrhntSAPGx+pYg4qPlzDasMTCVQluXKxqjf8CqByMXTuMkXeg9hysQy0dVd5EDHQNoRp4rxtfnkXFpItpB97VQccwjWTAimrl6IpaccbkZQ5BSZRWq7N0DUJ8cHmmHnLqwp1dmwRHRQlYNC5nirNSOZnEjB0qEbRl+xtpvDHOsiE94nWnAAW+fFxVsWSEyeLKl6r/+kk4t3QKbrmVg+xbIdfAKX8ZXQGsl2BctNAWmWIkw3+9hAvALRDLwF4oPLUIjF1c00rE4hg+p0gKscnpoocR43grncp52Si9V05iRSFoGDo4JhGjl85J9NjPXoXvLoMegLyZxivNoXlo/2q2wYYN1QXB0PB5ojiAaqshMZ2E0B5EAbDAEYK6HVv2rzbwkHNLgKJzS5KjPBhlwI0ucEvlEaUkbr/s0rT7iupiq3dLygZzLM04LwGO0QtGLl5WO5o/KNaDdJZgW3RI5BKkUbMFp2Yrltm2L72dGhY=
  - secure: hs1ejzwxcdm5Mn17hZ6Zwl53CrSH0mLKmwPpYmxDhl8wEOjuedb3hV35xuy++RKnyQjKrJIO8zpFyIRi1xtZDIxWmDxjZYSMLodEq7TiSTw6ZS1f3TZktPUi/Vu0WIHYhALiNB34RMeqpRcDcsmpimFPcBJlUDbyYpgzEyHz6Lw5n3/k5rT0CcUBIBu4zFcdCN7hVT/uI7zVuwEOeok/ku7aaE4rlRP5OXtXvzTrJWgrdvSUWcBjQZl0hA5F6Emk4QAAfVoEXO25hm4XHCtkb7H3oZu7CMHfnI01NCJKpKq7uWZ/x2NTTR7OVeWZHchKR0JgOBxIVoaHd0k1R0mSiHj5n/ldROZxJK+aDkGidB2Hpah6OXlyEEBOAj475QE8PkssSeGMZKH2sG/z4NfBTMMXd/Jkv6eIRGmiLNEtim4+trd/UfDgGftvyqDVEZlPT3/wx/AZUebwjwW6vAp7VUxpqf1XHdO2D19+ZQJsaD0BmELq5Gd2ZRHD5eqZA+DVKKnzmiobiXPjBDrjtOtrKHBUT3DyGdAYX7d0eEfRV56ZT2d8i32Z/qQbwFsv1e7Z7RrWTglW4dPaJKKVTyhrn704ot7xy07b6RK6dbRvOfH5Gw1rGIBsc9+xUHp+pd7EGVPv3NkCw0TBhS9AMaJ1fiOzNuDf19XdOTB0eJP5mgQ=

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
