language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master
  - develop

before_script: openssl aes-256-cbc -K $encrypted_d89d1ce6e9a7_key -iv $encrypted_d89d1ce6e9a7_iv -in secring.gpg.enc -out secring.gpg -d

script:
- ./gradlew clean build uploadArchives --info

env:
  global:
  - secure: jYLzkKzA3GPjc2hgNSvfCkpuGN8vS6tf8aA5mkDGLEeGAkTzu55aU9XRJM60pB+uIl3hRQf0CO5hj6wRe0wUgnSdHghvOkXGST++Yc7qOg+HFUbzRtmMP1aproADsH7MmYR6mzPlSKRD3rEKmlffD71pCqJz9FJW3Ptu+yRwlHSfZP49dOMcd6AzPy8eCdrhUgM6S4Cjpuhiq8BhiUQIjRHijwQ6kYk6Q0d+BRxCW9wT8b1D9iMWhug4YcxK4SPwjeV6QtLjqTj+ptZKUVxAvUigNDtpQGRayZay3EF2RsjeqBAV2HB6FR5lJahbU6ylm0PUF+I3UbG3N9wIkbPqG8Sbfax3kMUli+yYc2YAeiRgw170DAy+u1yrg36BdkUcZL5KQ0daAVB7dMSeJjrX+U8JK6SaW+BkaCuS/fnJ6mjphSalL/RU5Voqpr1GQPe1ol/I5v80V+o+yEqS8HvgQLBA3XpF/fOqkG0bAlUASXP+ut4fOq40kat9Y4s+abHEnu+7sRI+TklH9+JHoh2QGd5KJM+Z+7qJy3ThVIDb4FFRjYR5XmModZ3kjH5rofs5Rxuy1brd1qM8vnu2wxFHtKbUe2WxomS2tjn1Zftz828GxYWq8C9n9PeyCLYJrh/jSNPnCuroJJHBDGxG0Fy60dTsuE9DusUQprxu7llsS6c=
  - secure: k5TfUm3r71v54SwNJ0zF0iHf4B/WFSaoHpRYG8fBTS0Z5RwPfCEFbQsdpT4VHBZrVkflgCOHuXr2DknnH5cVfAzi1XG/gthJX/pX23m+nq+ix+EjClkIQm/buhOhlFtlJTBK5vJg7EBbbdkcL/4/+Vfs5/r+jB7GzTrHrnGN3sIQaGvwYzR8U+bMbCpdYvVjYV7l9VBwNrIwXJs+n96WNJp2qYB1xDMBALVUAgIqGteR/cl4wzIBI9sX5S09lmFqYxFLY+yXYsDY5Vw60PWpTxuLfzLmzowPXhabZbRsw89vIt1mWX81gDs5lxnlYDnXn7PQNAnbNhrlI23k65smJ0E0+Q+Av+jvUJuyUMccL7R0DL716P4chnZIEZmHs1mLKtUFEf5qIl4MnGVXn82m3NVQnl8mhSqxnFce7GglKSCFqcf+NmlmcoKbEs4Xu/xaiASabBxrn2knlonf9xxe6ErHjtGZ5abmsmKu2kz1fKstHbj8pniJunlhX+Z+94KXIzZj/6ySMjik/kyLt32smTsMT8bQliCdAYNqgPT3m324Bk76i+vfCz9/gP3e/lxUIVUMcRZ/4DVLaWuoTtbnxaRhIYe3aIZtZdrQFhlt2f479jqfq3Yd2NSD6UH+rFhuvK+F8CS242PohXlN1uvf1q9CpMjksWrRvzovsKLTZHo=
  - secure: GjS/BkWW9gkhH8EIt4vV4arGfyFLXdOEmw21TxNEaHDOZCKCegz1MfN2vpoq2P8fWgEWTZBmHgZZzEWFdd9TUBw28LXj6Ul43VXnQ+Y/AjSV//2pEcr3Ix/Os37ZVf2/NieeAsPuhfgcr7aaC7Dr98p8j/2XX4SepiONaWcxyL9QNpMXi0ICC4G8uncnhaBmUqTdOcb4povsAv36imgk+Z46Epk4fE5+3PIAquxfLWpw1CeHu5x87jsMuxvKG8BYzfEEHNwowkaM/72MZkYKmtiFx0lHgwTWHsGNmFBVUaCNZYB7+CBaFMAYJJrKFSVuu0e1O5eIKST1moUo6hG/0Ie7qPEXDR0QQLdNLRCjwd4W0oWBMgBKtL9JrQmGuSVyFF+Yj+0KA70wNhlxAuZmkAYzZY63bKCFE7tq9aGrYiu+7jxJPFJowSOVou/sxdPwDrL2lF4buH0Y8Xq0daZWCUI8ssE3qOXDDMH7Q/Nmu+J5hR/i6zSTjfW3i6sdjteHo50Tg+/Rfc/Pg5XuDx3UsyDSOKNwWkiX9/0cRCHkbtOpZ8NqBGZLtR4BcE5+2U9AHdeboFtnBls+o4X75pp8ICgk5CJBlyR31QEIfnhtUxBsAA6pS1cGnm+T9PqnLqS4BLtCDGt+cQueDsTQVwIYh4DlReh48vPdf8tnN4O+HQY=
  - secure: iHiYQN4PoSbdLp1qk5Hf4QuNN5E27Ob0D2ZNriZyD+kRncgTE/ZDfi2drjx2JDJIoiUFnYVpEL9/rXD43/LtipT14+a8OeBd6yUWwiSElz/j+EWIHctufE/C87En2TSl+5jnSR2fn592+GnUpRBoK3VVKcDTFp5ajooNEjZq29ImVeV/5uBFW665wFY6UyIqcxGPX4qaCGoTNIEshl8K/8j9ap9UQjfU4E8MFSlRatrjPHcZc5PSBhQPLKT5rsXjq7l2ghuRT5ic87/9OF5TkUBrswEbS6TphbUGYLCvnWewVx1b3qgbv4M9RdAm3f6mdsxoc4wtJMLxGtQEACK4O3YkK0EpNuX/g1LCeEkH1/v+pp5GMG3jvMGYqWbI6p2zBjspSDRuQRcA5Q2RHUFzJvJM8n/e8kBepUOwutO5C18y4ymjJH8uQeE1GlxuAkuFHJwF7p9ESdyxbmztgAkJ4FphlWZu+N6XhV6tD+ZbXSXz2T1YqsDZWu1slX5lJ5YvJOyAguMctNi5pehVP3+oKCnlMi9b8uujWMSgkYv6v14mRI8IOHcWwMu3OKRs2IuXFjfNHXaGmIPyvyoDjYqup9A4tlm1onuN/9Qa2KEUoICzBPyoe7J1Jap5eIuVZoMrvbvlFHVSZf5L7MOAgAcF1XtfFJm6iXpPWIQoid1Tekc=

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
